name: Osteopathy
favicon: null
layout_spectrum: 0.10619380255229771
typography_spectrum: 0.6324251552578062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.48556978651322424
  lightness: 0.9142848197370768
  saturation: 0.5320818244945258
  rhythmicContrast: 0.5452884866390377
purpose: []
