name: Osteopathy
analytics:
  twitter: rob.cartwright
purpose: []
github: true
description: Educational site
cta:
  bucket: null
  version: null
  domain: null
author:
  name: 'Robert Cartwright DO, ND, LicAc. '
  email: rob.cartwright@me.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.10619380255229771
color:
  lightness: 0.9142848197370768
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  saturation: 0.5320818244945258
  brandStrength: 0.48556978651322424
  rhythmicContrast: 0.5452884866390377
content_rating:
  adult: false
typography_spectrum: 0.6324251552578062
opengraph: {}
title: The History of Research into the Effects of the Osteopathic Lesion
